recipes = "~/recipes"

[web]
port = "8080"

[planner]
color = "#3A5B7E"
first_day_of_week = "sunday"
scroll_offset = 3
scroll_amount = 15
ignore_ingredients = [
  "water",
]

[planner.keys]
quit = "ctrl+c"
main_view = "q" # ie close help
help = "h"
shopping_list = "s"
focus = "f"
recipes = "0"
down = "j"
up = "k"
scroll_down="ctrl+d"
scroll_up="ctrl+u"
day_1 = "1"
day_2 = "2"
day_3 = "3"
day_4 = "4"
day_5 = "5"
day_6 = "6"
day_7 = "7"
shopping_list_toggle = "t"
