recipes = "~/recipes"

[web]
port = "8080"

[planner]
color = "#7E4B8C"
first_day_of_week = "sunday"

[planner.keys]
quit = "ctrl+c"
main_view = "q" # ie close help
help = "h"
focus = "f"
recipes = "0"
day_1 = "1"
day_2 = "2"
day_3 = "3"
day_4 = "4"
day_5 = "5"
day_6 = "6"
day_7 = "7"
