services:
  web:
    image: golang:latest
    restart: unless-stopped
    stop_grace_period: 1s
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "8080:8080"
    volumes:
      - $HOME/recipes:/root/recipes
      - .:/root/app
    command: >
      sh -c "cd /root/app && go run ./cmd/web"
