name = "Butter Chicken"
category = "Entrees"
include_in_cookbook = true
source = "https://www.youtube.com/watch?v=ESqF6CW91UQ"

[[parts]]
name = "Chicken"
ingredients = [
  { name = "boneless/skinless chicken thighs", quantity = "2", unit = "lbs" },
  { name = "kosher salt", quantity = "1", unit = "Tbsp" },
  { name = "garlic (minced)", quantity = "3", unit = "cloves" },
  { name = "minced ginger", quantity = "2", unit = "Tbsp" },
  { name = "lemon juice", quantity = "1/2", unit = "Tbsp" },
  { name = "garam masala", quantity = "1", unit = "tsp" },
  { name = "paprika", quantity = "1", unit = "Tbsp" },
  { name = "greek yogurt", quantity = "3/4", unit = "cup" },
  { name = "canola oil", quantity = "25", unit = "g" },
]

steps = [
  "Combine and marinade for a half hour.",
  "Preheat over to 450F and bake until internal temp is 165F.",
  "Broil with each side facing up until a little charred.",
]

[[parts]]
name = "Sauce"

ingredients = [
  { unit = "extra virgin olive oil" },
  { name = "white onion (diced)", quantity = "1", unit = "small" },
  { name = "pablano pepper (diced)", quantity = "1", unit = "small" },
  { name = "white onion", quantity = "1", unit = "small" },
  { name = "kosher salt", unit = "large pinch" },
  { name = "Minced Ginger", quantity = "2", unit = "Tbsp" },
  { name = "Minced Garlic", quantity = "3", unit = "cloves" },
  { name = "garam masala", quantity = "1", unit = "Tbsp" },
  { name = "turmeric", quantity = "1", unit = "Tbsp" },
  { name = "cumin", quantity = "1", unit = "Tbsp" },
  { name = "coriander", quantity = "1", unit = "Tbsp" },
  { name = "paprika", quantity = "1", unit = "Tbsp" },
  { name = "kosher salt", quantity = "2", unit = "tsp" },
  { name = "tomato paste", quantity = "6", unit = "oz" },
  { name = "water", quantity = "1", unit = "3/4 cup" },
  { name = "sugar", quantity = "2", unit = "tsp" },
  { name = "coconut milk", quantity = "1", unit = "cup" },
  { name = "vegan butter", quantity = "3", unit = "Tbsp" },
]

steps = [
  "Do things!",
]

[[parts]]
name = "Garnish"

ingredients = [
  { name = "greek yogurt", quantity = "1/2", unit = "cup" },
  { name = "coconut milk", quantity = "1/2", unit = "cup" },
  { name = "salt", quantity = "1/2", unit = "tsp" },
]
