name = "Butter Chicken"
category = "Entrees"
include_in_cookbook = true
source = "https://www.youtube.com/watch?v=ESqF6CW91UQ"

[[parts]]
name = "Chicken"
ingredients = [
  { quantity = "2lbs", name = "boneless/skinless chicken thighs" },
  { quantity = "1", unit = "Tbsp", name = "kosher salt" },
  { quantity = "3", unit = "cloves", name = "grated garlic" },
  { quantity = "2", unit = "Tbsp", name = "grated ginger" },
  { quantity = "1/2", unit = "Tbsp", name = "lemon juice" },
  { quantity = "1", unit = "tsp", name = "garam masala" },
  { quantity = "1", unit = "Tbsp", name = "paprika" },
  { quantity = "3/4", unit = "cup", name = "greek yogurt" },
  { quantity = "25", unit = "g", name = "canola oil" },
]

steps = [
  "do stuff",
]

[[parts]]
name = "Sauce"

ingredients = [
  { name = "Extra Virgin Olive Oil" },
  { quantity = "1", name = "White Onion", note = "small diced" },
  { quantity = "1", name = "Poblano Pepper", note = "seeded and small diced" },
  { name = "large pinch salt" },
  { quantity = "2", unit = "Tbsp", name = "Minced Ginger" },
  { quantity = "3", unit = "cloves", name = "Minced Garlic" },
  { quantity = "1", unit = "Tbsp", name = "garam masala" },
  { quantity = "1", unit = "Tbsp", name = "turmeric" },
  { quantity = "1", unit = "Tbsp", name = "cumin" },
  { quantity = "1", unit = "Tbsp", name = "coriander" },
  { quantity = "1", unit = "Tbsp", name = "paprika" },
  { quantity = "2", unit = "tsp", name = "kosher salt" },
  { quantity = "6", unit = "oz", name = "tomato paste" },
  { quantity = "1 3/4", unit = "cup", name = "water" },
  { quantity = "2", unit = "tsp", name = "sugar" },
  { quantity = "1", unit = "cup", name = "coconut milk" },
  { quantity = "3", unit = "Tbsp", name = "vegan butter" },
]

steps = [
  "do stuff",
]

[[parts]]
name = "Garnish"

ingredients = [
  { quantity = "1/2", unit = "cup", name = "greek yogurt" },
  { quantity = "1/2", unit = "cup", name = "coconut milk" },
  { quantity = "1/2", unit = "tsp", name = "salt" },
]
