category = "Sauces and Seasonings"
name = "Pizza Sauce"

[[parts]]
ingredients = [
  { name = "Yellow Onion (diced)", unit = "1" },
  { name = "Garlic Clove (diced)", unit = "3-5" },
  { name = "Canned San Marzano Tomatoes", quantity = "28", unit = "oz" },
  { name = "Tomato Paste", quantity = "6", unit = "oz" },
  { name = "Dried Basil", quantity = "2", unit = "tsp" },
  { name = "Dried Oregano", quantity = "2", unit = "tsp" },
  { name = "Black Pepper (freshly ground)", quantity = "1", unit = "tsp" },
  { name = "Kosher Salt", quantity = "1", unit = "tsp" },
]

steps = [
  "Brown the onion in a skillet with olive oil",
  "Add garlic and cook for a minute",
  "Add full can of tomatoes, juice and all",
  "Add tomato paste",
  "Stir to mix tomato paste well",
  "Add in all spices",
  "Stir, cover, and simmer for 1-2 hours, stirring occassionally"
]
