category = "Entrees"
name = "Pizza"

[[dependencies]]
recipe_id = "pizza-sauce"
replaces = "Pizza Sauce"
required = false

[[dependencies]]
recipe_id = "pizza-dough"
required = true

[[parts]]
ingredients = [
  ["Pizza Sauce", "4", "cup"],
  ["Pepperoni", "1", "cup"],
  ["Bell Peppers (sliced)", "1", "cup"],
  ["Onion (sliced)", "1", "cup"],
  ["Swiss Cheese (shredded)", "4", "cup"],
  ["Parmesan Cheese (grated)", "1/2", "cup"]
]

steps = [
  "Preheat oven to max",
  "Assemble pizza with sauce, cheese, and toppings and bake 8-10 minutes.",
]
