category = "Entrees"
name = "Pizza"

[[parts]]
ingredients = [
  { name = "Pizza Sauce", quantity = "4", unit = "cup", recipe_id = "pizza_sauce" },
  { name = "Pizza Dough", recipe_id = "pizza_dough" },
  { name = "Pepperoni", quantity = "1", unit = "cup" },
  { name = "Bell Peppers (sliced)", quantity = "1", unit = "cup" },
  { name = "Onion (sliced)", quantity = "1", unit = "cup" },
  { name = "Swiss Cheese (shredded)", quantity = "4", unit = "cup" },
  { name = "Parmesan Cheese (grated)", quantity = "1/2", unit = "cup" },
]

steps = [
  "Preheat oven to max",
  "Assemble pizza with sauce, cheese, and toppings and bake 8-10 minutes.",
]
