category = "Bread"
name = "Pizza Dough"
source = "some url here"

[[parts]]
prep_time = 1440

ingredients = [
  { name = "All-Purpose Flour", quantity = "1000", unit = "g" },
  { name = "Fine Sea Salt", quantity = "4", unit = "tsp" },
  { name = "Active Dry Yeast", quantity = "1/2", unit = "tsp" },
  { name = "Water (warm)", quantity = "3", unit = "cup" },
]

steps = [
  "Combine and whisk dry ingredients in a large bowl.",
  "Gradually add water and stir with wooden spoon until combined.",
  "Cover and place in oven with light and heat off for 18-24 hours.",
  "Transfer to a floured surface and divide into 6 equal portions.",
]
